name: Neocities

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    secrets:
      NEOCITIES_API_KEY:
        required: true

env:
  PNPM_VERSION: 10
  NODE_VERSION: 23

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: site
          path: dist

  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: neocities
      cancel-in-progress: true
    needs: build
    environment:
      name: 'production'

    steps:
      - uses: actions/download-artifact@v6
        with:
          name: site
          path: dist

      - uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_KEY }}
          cleanup: true
          neocities_supporter: false
          preview_before_deploy: true
          dist_dir: dist
