name: Check status.cafe

on:
  schedule:
    - cron: '12/15 * * * *'
  workflow_dispatch:

env:
  STATUS_CAFE_USERNAME: mocha8686

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.last-status-restore.outputs.cache-hit }}
    steps:
      - name: Retrieve latest status
        run: |
          curl "https://status.cafe/users/$STATUS_CAFE_USERNAME/status.json" > status.json

      - name: Get last status from cache
        uses: actions/cache/restore@v4
        id: last-status-restore
        with:
          path: status.json
          key: status-${{ env.STATUS_CAFE_USERNAME }}

      - name: Save latest status
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: status.json
          key: ${{ steps.last-status-restore.outputs.cache-primary-key }}

  deploy:
    uses: ./.github/workflows/neocities.yml
    needs: check
    if: ${{ needs.check.outputs.cache-hit != 'true' }}
    secrets: inherit
